sudo: enabled
language: node_js
  - "6"

cache:
  directories:
    - node_modules

# before_install:
#   - docker build -t jellyfish/lucent-dasboard .

# script:
#   - docker run jellyfish/lucent-dasboard npm run test

script:
  - npm run test

# deploy:
#   - provider: script
#     skip_cleanup: true
#     script: chmod +x ./deploy/deploy-travis.sh && ./deploy/deploy-travis.sh
#     on:
#       branch: master