sudo: enabled
language: node_js
  - lts/*
  
cache:
  directories:
    - node_modules

script:
  - pwd
  - chmod +x ./deploy/deploy-travis.sh && ./deploy/deploy-travis.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: pwd && chmod +x ./deploy/deploy-travis.sh && ./deploy/deploy-travis.sh
    on:
      branch: 17-feature-cicd
