sudo: enabled
language: node_js
  - lts/*
  
cache:
  directories:
    - node_modules

script:
  - pwd

deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x /home/travis/build/favians/Vue/deploy/deploy-travis.sh && /home/travis/build/favians/Vue/deploy/deploy-travis.sh
    on:
      branch: 17-feature-cicd
